/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as innoHuntSol from "./InnoHunt.sol";
export type { innoHuntSol };
export type { InnoHuntToken } from "./InnoHuntToken";
