/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InnoHuntInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRICE_CHANGE_THRESHOLD"
      | "buyShares"
      | "createProject"
      | "projectTokens"
      | "projects"
      | "sellShares"
      | "totalProjects"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PRICE_CHANGE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyShares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProject",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "projectTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellShares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalProjects",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PRICE_CHANGE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalProjects",
    data: BytesLike
  ): Result;
}

export interface InnoHunt extends BaseContract {
  connect(runner?: ContractRunner | null): InnoHunt;
  waitForDeployment(): Promise<this>;

  interface: InnoHuntInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRICE_CHANGE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  buyShares: TypedContractMethod<
    [projectId: BigNumberish, _amount: BigNumberish],
    [void],
    "payable"
  >;

  createProject: TypedContractMethod<
    [
      name: string,
      symbol: string,
      _minProposalThreshold: BigNumberish,
      _minVoteThreshold: BigNumberish,
      _shareprice: BigNumberish,
      _totalshares: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  projectTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        owner: string;
        name: string;
        totalShares: bigint;
        remainingShares: bigint;
        shareprice: bigint;
        minProposalThreshold: bigint;
        minVoteThreshold: bigint;
        proposalCount: bigint;
      }
    ],
    "view"
  >;

  sellShares: TypedContractMethod<
    [projectId: BigNumberish, _amount: BigNumberish],
    [void],
    "payable"
  >;

  totalProjects: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRICE_CHANGE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyShares"
  ): TypedContractMethod<
    [projectId: BigNumberish, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      _minProposalThreshold: BigNumberish,
      _minVoteThreshold: BigNumberish,
      _shareprice: BigNumberish,
      _totalshares: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "projectTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        owner: string;
        name: string;
        totalShares: bigint;
        remainingShares: bigint;
        shareprice: bigint;
        minProposalThreshold: bigint;
        minVoteThreshold: bigint;
        proposalCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sellShares"
  ): TypedContractMethod<
    [projectId: BigNumberish, _amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "totalProjects"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
